# Generated by Django 4.0.4 on 2022-05-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_programminglanguages_projects_subject_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='topics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.topics'),
        ),
    ]
