# Generated by Django 4.0.4 on 2022-05-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_subjects_subject_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='topics',
        ),
    ]
