# Generated by Django 4.0.4 on 2022-05-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_subject_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectDescription',
            field=models.TextField(default=2, max_length=500),
        ),
    ]
