# Generated by Django 4.0.4 on 2022-05-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projects_projectdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='topicsSubject',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
