# Generated by Django 4.0.4 on 2022-05-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonProgrammingLanguages',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
