# Generated by Django 4.0.4 on 2022-05-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_nonprogramminglanguages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=4000)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectLink',
            field=models.TextField(max_length=200),
        ),
    ]
