# Generated by Django 4.0.4 on 2022-05-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tech',
            name='creationYear',
            field=models.IntegerField(max_length=4),
        ),
    ]
