# Generated by Django 4.0.4 on 2022-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_tech_img_alter_tech_creationyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='img',
        ),
        migrations.AddField(
            model_name='tech',
            name='imgLink',
            field=models.CharField(default='Nothing', max_length=100),
        ),
    ]
