# Generated by Django 4.0.4 on 2022-06-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_labs_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='imgLink',
        ),
        migrations.AddField(
            model_name='tech',
            name='imageUrl',
            field=models.URLField(default='url'),
        ),
        migrations.AlterField(
            model_name='labs',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='imgLink',
            field=models.URLField(),
        ),
    ]
