# Generated by Django 4.0.4 on 2022-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_tech_imglink_tech_imageurl_alter_labs_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsLink',
            field=models.URLField(default='URl'),
        ),
    ]
