# Generated by Django 4.0.4 on 2022-06-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_news_newslink'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('imageUrl', models.URLField()),
            ],
        ),
    ]
