# Generated by Django 4.0.4 on 2022-06-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_blogsanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='creationYear',
            field=models.IntegerField(),
        ),
    ]
