# Generated by Django 4.0.4 on 2022-06-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_remove_tech_creationyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='creationYear',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
    ]
