# Generated by Django 4.0.4 on 2022-06-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_tech_creationyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='creationYear',
            field=models.IntegerField(default=1),
        ),
    ]
