# Generated by Django 4.0.4 on 2022-06-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_tech_creationyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='creationYear',
        ),
    ]
