# Generated by Django 4.0.4 on 2022-06-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_remove_tech_creationyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
