# Generated by Django 4.0.4 on 2022-06-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_tech_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labs',
            name='title',
        ),
        migrations.AddField(
            model_name='labs',
            name='name',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
