# Generated by Django 4.0.4 on 2022-06-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_remove_labs_title_labs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
