# Generated by Django 4.0.5 on 2022-06-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_remove_blogsanswers_imageurl_remove_news_imglink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectImage',
            field=models.ImageField(default='null', upload_to='ProjectImages/'),
            preserve_default=False,
        ),
    ]
