# Generated by Django 4.0.5 on 2022-06-05 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsanswers',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
