# Generated by Django 4.0.5 on 2022-06-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_blogsanswers_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsanswers',
            name='image',
        ),
    ]
