# Generated by Django 4.0.5 on 2022-06-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_remove_blogsanswers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsanswers',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
