# Generated by Django 4.0.5 on 2022-06-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_alter_blogsanswers_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='tfcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('advisor', models.CharField(max_length=50)),
                ('year', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='tfcsImages/')),
                ('reportLink', models.CharField(max_length=500)),
                ('gitLink', models.CharField(max_length=500)),
            ],
        ),
    ]
