# Generated by Django 4.0.5 on 2022-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_tfcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfcs',
            name='resume',
            field=models.TextField(default='Resume', max_length=2000),
        ),
    ]
