# Generated by Django 4.0.5 on 2022-06-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_alter_tfcs_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfcs',
            name='year',
            field=models.IntegerField(default=2022, max_length=4),
        ),
    ]
